//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.24 at 02:33:13 PM IST 
//


package org.example.demo.ui.response;

import lombok.Data;

import jakarta.xml.bind.annotation.*;
import org.example.demo.domain.model.Country;


@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"country"})
@Data
@XmlRootElement(name = "findCountryResponse")
public class FindCountryResponse {
    @XmlElement(required = true)
    private Country country;

}
