//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.24 at 02:33:13 PM IST 
//


package org.example.demo.ui.response;

import jakarta.xml.bind.annotation.*;
import lombok.Data;
@Data
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"id", "name", "age"})
@XmlRootElement(name = "getStudentResponse")
public class GetStudentResponse {

    private int id;
    @XmlElement(required = true)
    private String name;
    private int age;

}
