//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.24 at 02:33:13 PM IST 
//


package org.example.demo.domain.model;

import jakarta.xml.bind.annotation.*;
import lombok.Data;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Country", propOrder = {"name", "code", "currency"})
@Data
public class Country {
    @XmlElement(required = true)
    private String name;
    @XmlElement(required = true)
    private String code;
    @XmlElement(required = true)
    private String currency;
}
